---

name: Feature request
description: Suggest an idea for this project
title: "Feature: "
labels: ['enhancement', 'triage']

body:
  - type: markdown
    attributes:
      value: |
        Please make sure to go through these steps **before opening an issue**:
        
        - [ ] Read the documentation to make sure the feature does not yet exist: [Docs](https://github.com/ansibleguy/collection_opnsense/tree/latest/docs)
        
        - [ ] Only API-Enabled configuration can be implemented!
        
            Make sure the feature is already implemented on the OPNSense-side: [API Docs](https://docs.opnsense.org/development/api.html)
        
            Else you may want to create an issue in one of the [OPNSense repositories](https://github.com/opnsense)

  - type: textarea
    id: api
    attributes:
      label: Link to API
      description: |
        Please provide the link to the API that should be implemented! (https://docs.opnsense.org/development/api/PLACEHOLDER/PLACEHOLDER.html)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        A clear and concise description of:
        
        * what you want to happen
        * what you are missing
        * why that would be beneficial
    validations:
      required: true
